os: Visual Studio 2017
platform: x64

environment:
    CC:  C:/cygwin64/bin/gcc
    CXX: C:/cygwin64/bin/g++
    FC:  C:/cygwin64/bin/gfortran
    SHELL: C:\cygwin64\bin\bash

cache:
  - C:\cmk -> .appveyor.yml


install:
  - cmd: C:\cygwin64\setup-x86_64.exe -q -P gcc-core,gcc-g++,gcc-fortran,libncurses-devel,zlib-devel
  - ps: |
        if (-Not (Test-Path "C:\cmk" -PathType Container) ) {
          $env:CMAKE_URL = "https://cmake.org/files/v3.12/cmake-3.12.0.tar.gz"
          $env:CMAKE_ZIP = "C:\cmake-3.12.0.tar.gz"
          (New-Object System.Net.WebClient).DownloadFile($env:CMAKE_URL, $env:CMAKE_ZIP)
        }
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set PATH=C:\cygwin64\bin;%PATH%
  - cmd: bash -lc "[[ -d /cygdrive/c/cmk ]] || tar -xzf /cygdrive/c/cmake-3.12.0.tar.gz"
  - cmd: bash -lc "[[ -d /cygdrive/c/cmk ]] || { cd cmake-3.12.0 && ./bootstrap --prefix=/cygdrive/c/cmk && make && make install; }"

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: mkdir build
  - cmd: cd build
  - cmd: set PATH=C:\cygwin64\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - cmd: set CMAKE_PREFIX_PATH=C:\cygwin64
  - cmd: bash -lc "export PATH=/cygdrive/c/cmk/bin:$PATH; cd $APPVEYOR_BUILD_FOLDER/build && cmake -G 'Unix Makefiles' ..;"
  - cmd: bash -lc "export PATH=/cygdrive/c/cmk/bin:$PATH; cd $APPVEYOR_BUILD_FOLDER/build && cmake --build . -- -j2;"

#test_script:
#  - ps: $env:CMAKE --build . --target install

test: off