os: Visual Studio 2017
platform: x64

environment:
    CC:  /cygdrive/c/cygwin64/bin/gcc
    CXX: /cygdrive/c/cygwin64/bin/g++
    FC:  /cygdrive/c/cygwin64/bin/gfortran
    SHELL: C:\cygwin64\bin\bash

install:
  - cmd: C:\cygwin64\setup-x86_64.exe -q -P binutils,gcc-core,gcc-g++,gcc-fortran,libncurses-devel,zlib-devel,libuv1,librhash0,libuuid1,libjsoncpp19,libarchive13,cmake
  - cmd: set PATH=C:\cygwin64\bin;%PATH%

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: mkdir build
  - cmd: cd build
  - cmd: set PATH=C:\cygwin64\bin;%PATH%
  - cmd: echo %PATH%
  - cmd: bash -lc "cd $APPVEYOR_BUILD_FOLDER/build && cmake -G 'Unix Makefiles' ..;"
  - cmd: bash -lc "cd $APPVEYOR_BUILD_FOLDER/build && cmake --build . -- -j2;"

#test_script:
#  - ps: $env:CMAKE --build . --target install

test: off
