!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
MODULE MODD_SPLINES

INTEGER, PARAMETER :: NMAX=2000
INTEGER, PARAMETER :: NORDMAX=2
INTEGER, PARAMETER :: NSDMAX=20

REAL, DIMENSION(:,:,:), ALLOCATABLE :: AI
INTEGER, DIMENSION(:,:), ALLOCATABLE :: NS
REAL, DIMENSION(:,:,:), ALLOCATABLE :: ZS
REAL, DIMENSION(:,:,:,:), ALLOCATABLE:: XS

END MODULE MODD_SPLINES
