!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
MODULE MODE_MODELN_SURFEX_HANDLER
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE 

INTEGER :: ICURRENT_MODEL = -1
!$OMP THREADPRIVATE(ICURRENT_MODEL)

CONTAINS 
!
SUBROUTINE INIT_CURRENT_MODEL_INDEX_SURFEX()
!
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_SURFEX_HANDLER:INIT_CURRENT_MODEL_INDEX_SURFEX',0,ZHOOK_HANDLE)
ICURRENT_MODEL = -1
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_SURFEX_HANDLER:INIT_CURRENT_MODEL_INDEX_SURFEX',1,ZHOOK_HANDLE)
!
END SUBROUTINE INIT_CURRENT_MODEL_INDEX_SURFEX
!
FUNCTION GET_CURRENT_MODEL_INDEX_SURFEX()
INTEGER :: GET_CURRENT_MODEL_INDEX_SURFEX
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_SURFEX_HANDLER:GET_CURRENT_MODEL_INDEX_SURFEX',0,ZHOOK_HANDLE)
GET_CURRENT_MODEL_INDEX_SURFEX = ICURRENT_MODEL
IF (LHOOK) CALL DR_HOOK('MODE_MODELN_SURFEX_HANDLER:GET_CURRENT_MODEL_INDEX_SURFEX',1,ZHOOK_HANDLE)
!
END FUNCTION GET_CURRENT_MODEL_INDEX_SURFEX
!
END MODULE MODE_MODELN_SURFEX_HANDLER

