!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
!     #########
SUBROUTINE READ_NAMELISTS_WATFLUX_n (WM, HPROGRAM,HINIT)
!     #######################################################
!
! --------------------------------------------------------------------------
!
!
!
USE MODD_SURFEX_n, ONLY : WATFLUX_MODEL_t
!
USE MODN_WATFLUX_n
!
USE MODI_DEFAULT_WATFLUX
USE MODI_DEFAULT_CH_DEP
USE MODI_DEFAULT_DIAG_WATFLUX
USE MODI_READ_DEFAULT_WATFLUX_n
USE MODI_READ_WATFLUX_CONF_n
!
USE MODI_READ_NAM_PREP_WATFLUX_n
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODI_READ_WATFLUX_CONF_n
IMPLICIT NONE
!
!
TYPE(WATFLUX_MODEL_t), INTENT(INOUT) :: WM
!
 CHARACTER(LEN=6),   INTENT(IN)  :: HPROGRAM  ! program calling surf. schemes
 CHARACTER(LEN=3),   INTENT(IN)  :: HINIT     ! choice of fields to initialize
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-----------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('READ_NAMELISTS_WATFLUX_N',0,ZHOOK_HANDLE)
 CALL DEFAULT_WATFLUX(XTSTEP,XOUT_TSTEP,CWAT_ALB,CINTERPOL_TS)
!
 CALL DEFAULT_CH_DEP(CCH_DRY_DEP)
!
 CALL DEFAULT_DIAG_WATFLUX(N2M,LSURF_BUDGET,L2M_MIN_ZS,LRAD_BUDGET,LCOEF,LSURF_VARS, &
                           LSURF_BUDGETC,LRESET_BUDGETC,XDIAG_TSTEP        )
!
 CALL READ_DEFAULT_WATFLUX_n(WM%CHW, WM%DWO, WM%W, HPROGRAM)
!
 CALL READ_WATFLUX_CONF_n(WM%CHW, WM%DWO, WM%W, HPROGRAM)
!
!----------------------------------------------------------------------------
!
IF (HINIT=='PRE') CALL READ_NAM_PREP_WATFLUX_n(HPROGRAM)
IF (LHOOK) CALL DR_HOOK('READ_NAMELISTS_WATFLUX_N',1,ZHOOK_HANDLE)
!
END SUBROUTINE READ_NAMELISTS_WATFLUX_n
