!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
SUBROUTINE SECOND_SFX(KT)
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
INTEGER :: KT
INTEGER :: IT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('SECOND_SFX',0,ZHOOK_HANDLE)
 CALL system('date +%s > tempo')
OPEN(UNIT=99,FILE='tempo')
READ(99,*)IT
CLOSE(99)
KT=IT
IF (LHOOK) CALL DR_HOOK('SECOND_SFX',1,ZHOOK_HANDLE)
END SUBROUTINE SECOND_SFX
