!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
SUBROUTINE SET_SURFEX_FILE_NAME_ASC(HNAME_IN,HNAME_OUT)
!
USE MODD_IO_SURF_ASC, ONLY : CFILEIN
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=28), OPTIONAL, INTENT(IN)     :: HNAME_IN
 CHARACTER(LEN=28), OPTIONAL, INTENT(OUT)    :: HNAME_OUT
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
IF (LHOOK) CALL DR_HOOK('SET_SURFEX_FILE_NAME_ASC',0,ZHOOK_HANDLE)
!
IF (PRESENT(HNAME_IN)) THEN
  CFILEIN=HNAME_IN
ELSEIF (PRESENT(HNAME_OUT)) THEN
  HNAME_OUT=CFILEIN
ENDIF
!
IF (LHOOK) CALL DR_HOOK('SET_SURFEX_FILE_NAME_ASC',1,ZHOOK_HANDLE)
!
END SUBROUTINE SET_SURFEX_FILE_NAME_ASC
