#!/bin/sh
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
##
## Run Parameter
##

export TPN=${TPN-"1"}
export NBP=${NBP-"1"}
export TIME=${TIME-"3600"}
export MEM=${MEM-"3Gb"}
export MNH_EXP=${MNH_EXP-"MNH_EXP"}

export MPIRUN=${MPIRUN-"mpirun -nn ${NBP} -nnp ${TPN}"}
export MONORUN=${MONORUN-"mpirun -nn 1 -nnp 1"}
export CAT=${CAT-"cat"}

##
## exection directory
##

export SUBDIR=${SUBDIR-"${PWD}/${CONFEXP}"}
export EXECDIR=${EXECDIR-"\${TMPDIR}"}

##
## transfert protocole
##

export LINKFILES=${LINKFILES-"ln -sf "}

export INDIR=${INDIR-"INDIR"}
export OUTDIR=${OUTDIR-"${INDIR}"}

case "${INHOST}" in 

    "" ) # default --> FTDIR
    export GETFILES=${GETFILES-"ln -s "}
    export INDIR="${FTDIR}/${INDIR}"
    export RMINDIR="${INDIR}"
    #export GETFILES=${GETFILES-"ftget -h cougar "}
    export RMINDIR=${RMINDIR-"${INDIR}"}
    ;;
    
    *'@'*) # ssh transfert
    export GETFILES=${GETFILES-"scp"}
    export RMINDIR=${RMINDIR-"${INHOST}:${INDIR}"}
    ;;

    workdir) # get file from  $workdir
    export GETFILES=${GETFILES-"ln -s "}
    export INDIR="${WORKDIR}/${INDIR}"
    export RMINDIR="${INDIR}"
    ;;

esac

export OUTHOST=${OUTHOST-"${INHOST}"}

case "${OUTHOST}" in 
    
    "" ) # default --> FTDIR
    export PUTFILES=${PUTFILES-"cp -p"}  
    export RMMKDIR=${RMMKDIR-"mkdir -p"}
    export OUTDIR="${FTDIR}/${OUTDIR}"
    export RMOUTDIR=${RMOUTDIR-"${OUTDIR}"}
    ;;
    
    *'@'*) # ssh transfert
    export PUTFILES=${PUTFILES-"scp"} 
    export RMMKDIR=${RMMKDIR-"ssh -n ${OUTHOST} mkdir -p "}
    export RMOUTDIR=${RMOUTDIR-"${OUTHOST}:${OUTDIR}"}
    ;;

    workdir) # put files in $workdir
    export PUTFILES=${PUTFILES-"cp "} 
    export RMMKDIR=${RMMKDIR-"mkdir -p "}
    export OUTDIR="${FTDIR}/${OUTDIR}"
    export RMOUTDIR="${OUTDIR}"
    ;;

esac

export RMSHELL=${RMSHELL-"rsh yuki -n "}
export QSUB=${QSUB-"/usr/bin/nqsII/qsub"}

##
## Job Header
##

export JOBMONO="\
#PBS -S /bin/ksh             # ligne obligatoire specifiant le shell: ksh ou csh
#PBS -q vector                # classe multiple
#PBS -N R`basename  $PWD`    # noms requete
#PBS -l cpunum_job=${TPN}    # réservation de 4 processeurs (max=8)
#PBS -b ${NBP}
#PBS -j o                    # concatene la sortie standard avec l erreur standard
#PBS -l cputim_job=${TIME}      # temps max (HH:MM:SS)/job
#PBS -l memsz_job=${MEM}        # memoire max /job
"
export JOBMULTI=$JOBMONO

##
## Default Name of input/output files parameters ...
##

## PrepPgd

export PREP_PGD_FILES=${PREP_PGD_FILES-"/cnrm/ge/mrmh/mrmh005/mesonh/PGD"}

export OUT_CPGDFILE=${OUT_CPGDFILE-"OUT_CPGDFILE"}
export INP_CPGDFILE_FATHER=${INP_CPGDFILE_FATHER-"INP_CPGDFILE_FATHER"}

## PrepNest

export INP_YPGD1=${INP_YPGD1-"INP_YPGD1"}
export INP_YPGD2=${INP_YPGD2-"INP_YPGD2"}
export INP_YPGD3=${INP_YPGD3-"INP_YPGD3"}
export INP_YPGD4=${INP_YPGD4-"INP_YPGD4"}
export LISTGET=${LISTGET-"LISTGET"}
export CRT_YNEST=${CRT_YNEST-"CRT_YNEST"}
export OUT_YPGD1_NEST=${OUT_YPGD1_NEST-"OUT_YPGD1_NEST"}
export OUT_YPGD2_NEST=${OUT_YPGD2_NEST-"OUT_YPGD2_NEST"}
export LISTE_PUT=${LISTE_PUT-"LISTE_PUT"}

## PrepReal

export INDIR_HATMFILE=${INDIR_HATMFILE-"${RMINDIR}"}
export INP_HATMFILE=${INP_HATMFILE-"INP_HATMFILE"}
export SUF=${SUF-"SUF"}
export INP_HPGDFILE=${INP_HPGDFILE-"INP_HPGDFILE"}
export INP_CFILE=${INP_CFILE-"INP_CFILE"}
export OUT_CINIFILE=${OUT_CINIFILE-"OUT_CINIFILE"}

## Spawning

export INP_YDOMAIN=${INP_YDOMAIN-"INP_YDOMAIN"}
export INP_CINIFILE=${INP_CINIFILE-"INP_CINIFILE"}
export OUT_CINIFILE_SPA=${OUT_CINIFILE_SPA-"OUT_CINIFILE_SPA"}

## Mesonh

export INP_CINIFILE1=${INP_CINIFILE1-"INP_CINIFILE1"}
export INP_CINIFILE2=${INP_CINIFILE2-"INP_CINIFILE2"}
export CRT_CEXP=${CRT_CEXP-"CRT_CEXP"}
export CRT_CSEG=${CRT_CSEG-"CRT_CSEG"}
export OUT_XFMOUT=${OUT_XFMOUT-"OUT_XFMOUT"}

## Diag

export INP_YINIFILE=${INP_YINIFILE-"INP_YINIFILE"}
export CRT_YSUFFIX=${CRT_YSUFFIX-"CRT_YSUFFIX"}
export OUT_DIAG=${OUT_DIAG-"OUT_DIAG"}

## Conv2dia

export CRT_CVYSUFFIX=${CRT_CVYSUFFIX-"CRT_CVYSUFFIX"}
export OUT_CVFILE=${OUT_CVFILE-"OUT_CVFILE"}

## Diaprog

export INP_FILE1=${INP_FILE1-"INP_FILE1"}
export NOVISU==${NOVISU=-"!"}
export OUT_GMFILE=${OUT_GMFILE-"OUT_GMFILE"}

