!SFX_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!SFX_LIC This is part of the SURFEX software governed by the CeCILL-C licence
!SFX_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!SFX_LIC for details. version 1.
PROGRAM OI_MAIN
!
!
USE MODI_OI_CONTROL
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
USE MODD_OFF_SURFEX_n
!
!
IMPLICIT NONE
!
REAL (KIND=JPRB) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('OI_MAIN',0,ZHOOK_HANDLE)


 CALL SURFEX_ALLOC_LIST(1)
 YSC => YSURF_LIST(1)

 CALL OI_CONTROL(YSC, &
          LDINLINE = .FALSE.)

 CALL SURFEX_DEALLO_LIST

IF (LHOOK) CALL DR_HOOK('OI_MAIN',1,ZHOOK_HANDLE)

END PROGRAM OI_MAIN
